version: "3"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=simple_bank
      - POSTGRES_PASSWORD=123123
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:123123@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432" ,"--" , "/app/start.sh"]
    command: ["/app/main"]